import 'dart:async';
import 'dart:convert';
import 'dart:math';

import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../model/bank_account.dart';
import '../model/bank_connection.dart';
import '../services/banking/enable_banking_api.dart';
import '../services/banking/enable_banking_auth.dart';
import '../services/banking/enable_banking_config.dart';
import '../services/banking/enable_banking_credentials_store.dart';
import '../services/banking/enable_banking_deeplink_service.dart';
import '../services/banking/enable_banking_exception.dart';
import '../services/banking/models/aspsp.dart';
import '../services/banking/models/eb_account.dart';
import '../services/banking/models/eb_session.dart';
import '../services/database/repositories/account_repository.dart';
import '../services/database/repositories/bank_connection_repository.dart';
import 'accounts_provider.dart';

part 'banking_provider.g.dart';

/// Default consent validity when an ASPSP doesn't advertise its own maximum
/// (`Aspsp.maximumConsentValidity` is null): 90 days.
const _kDefaultConsentValidity = Duration(days: 90);

String _generateCsrfState({int length = 32}) {
  final random = Random.secure();
  final bytes = List<int>.generate(length, (_) => random.nextInt(256));
  return base64Url.encode(bytes).replaceAll('=', '');
}

/// Thrown by [ConnectBankFlow] actions on invalid input, e.g. an OAuth
/// callback whose `state` doesn't match the one generated by
/// [ConnectBankFlow.startConnection] (CSRF protection).
class ConnectBankFlowException implements Exception {
  final String message;

  const ConnectBankFlowException(this.message);

  @override
  String toString() => 'ConnectBankFlowException: $message';
}

/// One bank account chosen by the user on the import screen (Step 12),
/// carrying the customized name/icon/color alongside the source [EbAccount].
class BankAccountImportSelection {
  final EbAccount account;
  final String name;
  final String symbol;
  final int color;
  final num startingValue;

  const BankAccountImportSelection({
    required this.account,
    required this.name,
    required this.symbol,
    required this.color,
    this.startingValue = 0,
  });
}

/// Outcome of the last OAuth callback handled by [BankCallbackHandler]:
/// watched by the UI to report failures and to move on to the account
/// import screen once [connectionId] is set.
class BankCallbackState {
  final bool processing;
  final String? errorMessage;
  final int? connectionId;

  const BankCallbackState({
    this.processing = false,
    this.errorMessage,
    this.connectionId,
  });
}

/// State of the connect-a-bank wizard (country → ASPSP → consent → import),
/// held by [ConnectBankFlow]. Not persisted: a fresh flow starts empty.
class ConnectBankFlowState {
  final String? country;
  final List<Aspsp> aspsps;
  final String? csrfState;
  final bool authorizing;
  final EbSession? session;
  final List<EbAccount> importable;
  final int? connectionId;

  const ConnectBankFlowState({
    this.country,
    this.aspsps = const [],
    this.csrfState,
    this.authorizing = false,
    this.session,
    this.importable = const [],
    this.connectionId,
  });

  ConnectBankFlowState copyWith({
    String? country,
    List<Aspsp>? aspsps,
    String? csrfState,
    bool? authorizing,
    EbSession? session,
    List<EbAccount>? importable,
    int? connectionId,
  }) => ConnectBankFlowState(
    country: country ?? this.country,
    aspsps: aspsps ?? this.aspsps,
    csrfState: csrfState ?? this.csrfState,
    authorizing: authorizing ?? this.authorizing,
    session: session ?? this.session,
    importable: importable ?? this.importable,
    connectionId: connectionId ?? this.connectionId,
  );
}

@Riverpod(keepAlive: true)
EnableBankingCredentialsStore enableBankingCredentialsStore(Ref ref) =>
    const EnableBankingCredentialsStore();

@Riverpod(keepAlive: true)
EnableBankingAuth enableBankingAuth(Ref ref) => EnableBankingAuth();

@Riverpod(keepAlive: true)
EnableBankingApi enableBankingApi(Ref ref) => EnableBankingApi(
  auth: ref.watch(enableBankingAuthProvider),
  store: ref.watch(enableBankingCredentialsStoreProvider),
);

@Riverpod(keepAlive: true)
class EnableBankingSettings extends _$EnableBankingSettings {
  @override
  Future<EnableBankingConfig?> build() async {
    final store = ref.watch(enableBankingCredentialsStoreProvider);
    return store.readConfig();
  }

  Future<bool> hasCredentials() async {
    final store = ref.watch(enableBankingCredentialsStoreProvider);
    return store.hasCredentials();
  }

  Future<void> save({
    required String appId,
    required String privateKeyPem,
    required EnableBankingConfig config,
  }) async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() async {
      final store = ref.read(enableBankingCredentialsStoreProvider);
      await store.saveCredentials(
        appId: appId,
        privateKeyPem: privateKeyPem,
        config: config,
      );
      return store.readConfig();
    });
  }

  Future<void> clear() async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() async {
      final store = ref.read(enableBankingCredentialsStoreProvider);
      await store.clear();
      return null;
    });
  }
}

@Riverpod(keepAlive: true)
EnableBankingDeeplinkService enableBankingDeeplinkService(Ref ref) {
  final service = EnableBankingDeeplinkService();
  ref.onDispose(service.dispose);
  return service;
}

/// Listens for the `sossoldi://eb-callback` deep link and feeds it to
/// [ConnectBankFlow]. Kept alive for the whole app session because the
/// callback can land at any time, including on a cold start.
@Riverpod(keepAlive: true)
class BankCallbackHandler extends _$BankCallbackHandler {
  @override
  BankCallbackState build() {
    // The wizard is autoDispose, but the CSRF state it generates has to
    // survive the round trip to the bank's consent page in an external
    // browser: hold a listener on it for as long as callbacks can arrive.
    ref.listen(connectBankFlowProvider, (previous, next) {});
    unawaited(ref.read(enableBankingDeeplinkServiceProvider).start(handle));
    return const BankCallbackState();
  }

  /// Routes one callback: refusals and errors surface as
  /// [BankCallbackState.errorMessage], a valid `code` completes the flow.
  Future<void> handle(EnableBankingCallback callback) async {
    if (!callback.isSuccess) {
      state = BankCallbackState(errorMessage: callback.errorMessage);
      return;
    }

    if (ref.read(connectBankFlowProvider).csrfState == null) {
      state = const BankCallbackState(
        errorMessage: 'No bank connection in progress, please start again',
      );
      return;
    }

    state = const BankCallbackState(processing: true);
    try {
      await ref
          .read(connectBankFlowProvider.notifier)
          .completeConnection(
            code: callback.code!,
            returnedState: callback.state ?? '',
          );
      state = BankCallbackState(
        connectionId: ref.read(connectBankFlowProvider).connectionId,
      );
    } on ConnectBankFlowException catch (e) {
      state = BankCallbackState(errorMessage: e.message);
    } on EnableBankingException catch (e) {
      state = BankCallbackState(
        errorMessage: e.message ?? 'Could not connect to the bank',
      );
    }
  }

  /// Clears the last outcome once the UI has consumed it.
  void reset() => state = const BankCallbackState();
}

@Riverpod(keepAlive: true)
class BankConnections extends _$BankConnections {
  @override
  Future<List<BankConnection>> build() {
    return ref.watch(bankConnectionRepositoryProvider).selectAll();
  }
}

/// Drives the connect-a-bank wizard: pick a country/ASPSP, start the
/// Enable Banking authorization, and turn the resulting session into a
/// persisted [BankConnection]. Scoped to one flow (autoDispose) — a new
/// attempt starts from an empty [ConnectBankFlowState].
@riverpod
class ConnectBankFlow extends _$ConnectBankFlow {
  @override
  ConnectBankFlowState build() => const ConnectBankFlowState();

  Future<void> loadAspsps(String country) async {
    final aspsps = await ref
        .read(enableBankingApiProvider)
        .getAspsps(country: country);
    state = state.copyWith(country: country, aspsps: aspsps);
  }

  /// Starts the Enable Banking authorization for [aspsp], stores a fresh
  /// CSRF `state` token in [ConnectBankFlowState.csrfState] and returns the
  /// consent URL to open in an external browser.
  Future<String> startConnection(Aspsp aspsp) async {
    state = state.copyWith(authorizing: true);
    try {
      final csrfState = _generateCsrfState();
      final maxValidity = aspsp.maximumConsentValidity != null
          ? Duration(seconds: aspsp.maximumConsentValidity!)
          : _kDefaultConsentValidity;

      final authorization = await ref
          .read(enableBankingApiProvider)
          .startAuthorization(
            aspspName: aspsp.name,
            aspspCountry: aspsp.country,
            state: csrfState,
            validUntil: DateTime.now().toUtc().add(maxValidity),
          );

      state = state.copyWith(csrfState: csrfState);
      return authorization.url;
    } finally {
      state = state.copyWith(authorizing: false);
    }
  }

  /// Completes the OAuth callback: validates [returnedState] against the
  /// CSRF token saved by [startConnection], exchanges [code] for a session
  /// and persists it as a [BankConnection].
  Future<void> completeConnection({
    required String code,
    required String returnedState,
  }) async {
    if (state.csrfState == null || returnedState != state.csrfState) {
      throw const ConnectBankFlowException(
        'OAuth callback state does not match the authorization request',
      );
    }

    final session = await ref
        .read(enableBankingApiProvider)
        .createSession(code);
    final connection = await ref
        .read(bankConnectionRepositoryProvider)
        .insert(
          BankConnection(
            aspspName: session.aspspName,
            aspspCountry: session.aspspCountry,
            sessionId: session.sessionId,
            validUntil: session.validUntil,
            status: BankConnectionStatus.active,
            psuType: session.psuType,
          ),
        );
    ref.invalidate(bankConnectionsProvider);

    state = state.copyWith(
      session: session,
      importable: session.accounts,
      connectionId: connection.id,
    );
  }

  /// Persists the accounts the user picked on the import screen (Step 12),
  /// linked to the [BankConnection] created by [completeConnection].
  Future<void> importAccounts(
    List<BankAccountImportSelection> selections,
  ) async {
    final connectionId = state.connectionId;
    if (connectionId == null) {
      throw const ConnectBankFlowException(
        'No active bank connection to import accounts into',
      );
    }

    final accountRepository = ref.read(accountRepositoryProvider);
    for (final selection in selections) {
      await accountRepository.insert(
        BankAccount(
          name: selection.name,
          symbol: selection.symbol,
          color: selection.color,
          startingValue: selection.startingValue,
          active: true,
          countNetWorth: true,
          mainAccount: false,
          order: 0,
          ebAccountUid: selection.account.uid,
          ebConnectionId: connectionId,
          iban: selection.account.iban,
        ),
      );
    }

    ref.invalidate(accountsProvider);
    state = state.copyWith(importable: const []);
  }

  /// Revokes the Enable Banking session and turns [connection]'s imported
  /// accounts back into manual accounts; their history is kept.
  Future<void> disconnect(BankConnection connection) async {
    try {
      await ref
          .read(enableBankingApiProvider)
          .deleteSession(connection.sessionId);
    } on EnableBankingException {
      // Consent may already be expired/revoked on the ASPSP side; still
      // finalize the disconnection locally.
    }

    final accountRepository = ref.read(accountRepositoryProvider);
    final linked = await accountRepository.selectLinked();
    for (final account in linked) {
      if (account.ebConnectionId == connection.id) {
        await accountRepository.unlink(account.id!);
      }
    }

    await ref
        .read(bankConnectionRepositoryProvider)
        .markStatus(connection.id!, BankConnectionStatus.revoked);

    ref.invalidate(bankConnectionsProvider);
    ref.invalidate(accountsProvider);
  }
}
