import 'package:basic_utils/basic_utils.dart';
import 'package:flutter/foundation.dart';

const kEnableBankingKeySize = 4096;
const kEnableBankingCertificateValidityDays = 730;

/// A freshly generated BYOC key pair, ready for Enable Banking registration.
class EnableBankingKeyMaterial {
  final String privateKeyPem;
  final String certificatePem;

  const EnableBankingKeyMaterial({
    required this.privateKeyPem,
    required this.certificatePem,
  });
}

/// Generates an RSA key pair and a self-signed X.509 certificate for Enable
/// Banking BYOC registration, entirely on-device. Top-level so it can run on
/// a background isolate via [compute]: pure-Dart RSA generation at
/// [kEnableBankingKeySize] is CPU-heavy and can take tens of seconds.
EnableBankingKeyMaterial generateEnableBankingKeyMaterial(int keySize) {
  final pair = CryptoUtils.generateRSAKeyPair(keySize: keySize);
  final privateKey = pair.privateKey as RSAPrivateKey;
  final publicKey = pair.publicKey as RSAPublicKey;

  final csrPem = X509Utils.generateRsaCsrPem(
    {'CN': 'Sossoldi Enable Banking'},
    privateKey,
    publicKey,
  );
  final certificatePem = X509Utils.generateSelfSignedCertificate(
    privateKey,
    csrPem,
    kEnableBankingCertificateValidityDays,
  );

  return EnableBankingKeyMaterial(
    privateKeyPem: CryptoUtils.encodeRSAPrivateKeyToPem(privateKey),
    certificatePem: certificatePem,
  );
}

/// Wraps [generateEnableBankingKeyMaterial] behind a class, mirroring
/// `EnableBankingAuth`, so tests can override it with a fast fake instead of
/// running real RSA key generation.
class EnableBankingKeyGenerator {
  const EnableBankingKeyGenerator();

  Future<EnableBankingKeyMaterial> generate({
    int keySize = kEnableBankingKeySize,
  }) => compute(generateEnableBankingKeyMaterial, keySize);
}
